package com.example.visitorapp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Visitor entity stores master details of a person.
 * One person can have many visits over time.
 */
@Entity
@Table(name = "visitors")
public class Visitor {

    // Primary key generated by database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Visitor full name (required).
    @Column(nullable = false)
    private String name;

    // Optional home/office address.
    private String address;

    // Optional but unique phone so we can identify repeat visitors.
    @Column(unique = true)
    private String phone;

    // Optional but unique email so we can identify repeat visitors.
    @Column(unique = true)
    private String email;

    // Optional designation/job title.
    private String designation;

    // Getter/setter methods are used by JPA and JSON serialization.
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }
}
