package com.visitorapp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * Visit entity stores each meeting occurrence for a visitor.
 * This gives us full history and allows "last visited" lookups.
 *
 * Design choice:
 * Visitor profile is stored in Visitor table, and each visit event is separate.
 * This prevents overwriting older meeting events.
 */
@Entity
@Table(name = "visits")
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Visit {

    // Primary key generated by database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ToString.Include
    private Long id;

    // Many visits can belong to one visitor.
    // FetchType.LAZY means visitor details are loaded only when accessed.
    // Common mistake: accessing lazy fields outside transaction can trigger
    // LazyInitializationException in other designs.
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "visitor_id", nullable = false)
    private Visitor visitor;

    // Date-time when this person came for this meeting.
    @Column(nullable = false)
    @ToString.Include
    private LocalDateTime visitedAt;

    // Optional short reason for meeting.
    @ToString.Include
    private String purpose;

    // Optional detailed notes for this meeting.
    private String notes;

    /**
     * JPA-safe equality: two entities are equal only when both have non-null IDs
     * and those IDs are equal.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Visit other)) {
            return false;
        }
        return id != null && id.equals(other.id);
    }

    /**
     * Stable hash code recommended for JPA entities.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
