package com.visitorapp.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Visitor entity stores master details of a person.
 * One person can have many visits over time.
 *
 * Why @Entity:
 * Tells JPA/Hibernate to map this class to a database table.
 *
 * Why @Table(name = "visitors"):
 * Explicit table naming avoids default naming surprises.
 */
@Entity
@Table(name = "visitors")
@Getter
@Setter
@ToString(onlyExplicitlyIncluded = true)
public class Visitor {

    // Primary key generated by database.
    // GenerationType.IDENTITY lets DB auto-increment id values.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ToString.Include
    private Long id;

    // Visitor full name (required).
    @Column(nullable = false)
    @ToString.Include
    private String name;

    // Optional home/office address.
    private String address;

    // Optional but unique phone so we can identify repeat visitors.
    // Common mistake: unique fields + blank strings can create conflicts.
    // Better to send null for unknown phone/email.
    @Column(unique = true)
    private String phone;

    // Optional but unique email so we can identify repeat visitors.
    @Column(unique = true)
    private String email;

    // Optional designation/job title.
    private String designation;

    /**
     * JPA-safe equality: two entities are equal only when both have non-null IDs
     * and those IDs are equal.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Visitor other)) {
            return false;
        }
        return id != null && id.equals(other.id);
    }

    /**
     * Stable hash code recommended for JPA entities.
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
